const { app, BrowserWindow } = require('electron');
const path = require('path');

app.setName('Recall Flashcards Smoke Test');
app.setPath('userData', path.join(app.getPath('temp'), `recall-flashcards-smoke-${process.pid}`));

const fail = (message) => { throw new Error(message); };

app.whenReady().then(async () => {
  const window = new BrowserWindow({ show: false, webPreferences: { contextIsolation: true, nodeIntegration: false } });
  window.webContents.session.webRequest.onBeforeRequest((details, callback) => callback({ cancel: !details.url.startsWith('file://') && !details.url.startsWith('blob:') }));
  try {
    await window.loadFile(path.join(__dirname, 'index.html'));
    const result = await window.webContents.executeJavaScript(`
      (async () => {
        const wait = (ms) => new Promise(resolve => setTimeout(resolve, ms));
        const assert = (condition, message) => { if (!condition) throw new Error(message); };
        const click = (selector) => { const node = document.querySelector(selector); assert(node, 'Missing ' + selector); node.click(); return node; };
        await wait(180);

        assert(typeof state !== 'undefined', 'App state is unavailable');
        assert(state.sets.length === 1, 'Default study set was not created');
        assert(document.querySelector('#home') && document.querySelector('#homeStats'), 'Home dashboard did not render on launch');
        assert(document.querySelector('#homeRecentDecks').textContent.includes('No cards yet'), 'Home dashboard did not show its empty state');
        assert([...document.querySelectorAll('[data-revision-workspace]')].every(section => section.hidden), 'Home left revision screens visible below the dashboard');
        assert(!document.querySelector('[data-home-nav="add"]'), 'Add cards is still a standalone navigation item');
        click('[data-home-nav="library"]');
        click('#fullLibraryGrid [data-set]');
        assert(state.currentView === 'deck' && !document.querySelector('#openAddCardsBtn').disabled, 'Library did not open Deck cards with an available Add cards button');
        click('#openAddCardsBtn');
        assert(state.currentView === 'cards' && document.querySelector('#home').hidden && !document.querySelector('#create').hidden, 'Deck cards Add cards button did not open the creator');
        click('.brand');
        assert(state.currentView === 'home' && !document.querySelector('#home').hidden, 'Logo did not return to the dashboard');
        click('[data-home-nav="library"]');
        assert(!document.querySelector('#fullLibrary').hidden, 'Library navigation did not open the deck chooser');
        click('#fullLibraryClose');
        click('#settingsBtn');
        assert(!document.querySelector('#settingsMenu').hidden, 'Settings menu did not open');
        const aiToggle = document.querySelector('#aiEvaluationToggle');
        assert(aiToggle && !aiToggle.checked, 'AI evaluation must start disabled');
        aiToggle.checked = true; aiToggle.dispatchEvent(new Event('change', { bubbles: true }));
        assert(state.aiEnabled && localStorage.getItem('recall-ai-enabled-v1') === 'true', 'AI setting did not persist locally');
        aiToggle.checked = false; aiToggle.dispatchEvent(new Event('change', { bubbles: true }));
        assert(!state.aiEnabled, 'AI setting did not turn off');
        document.querySelector('#themeSelect').value = 'dark';
        document.querySelector('#themeSelect').dispatchEvent(new Event('change', { bubbles: true }));
        assert(document.documentElement.dataset.theme === 'dark', 'Dark theme setting did not apply');
        const styleOf = (selector) => getComputedStyle(document.querySelector(selector));
        for (let i = 0; i < 100 && styleOf('#toast').backgroundColor !== 'rgb(36, 54, 95)'; i++) await wait(20);
        assert(styleOf('#toast').backgroundColor === 'rgb(36, 54, 95)', 'Dark toast is not using a readable themed surface: ' + styleOf('#toast').backgroundColor);
        assert(styleOf('#newSetBtn').backgroundColor === 'rgb(23, 34, 59)', 'Dark library actions are not themed');
        assert(styleOf('.library-search').backgroundColor === 'rgb(17, 26, 49)', 'Dark library search is not themed');
        document.querySelector('#themeSelect').value = 'light';
        document.querySelector('#themeSelect').dispatchEvent(new Event('change', { bubbles: true }));
        assert(document.documentElement.dataset.theme === 'light', 'Light theme setting did not apply');
        document.querySelector('#keybindFlip').dispatchEvent(new KeyboardEvent('keydown', { key: 'q', bubbles: true }));
        assert(state.keybinds.flip === 'q', 'Custom keybind did not save');
        document.querySelector('#themeSelect').value = 'system';
        document.querySelector('#themeSelect').dispatchEvent(new Event('change', { bubbles: true }));
        click('#resetKeybindsBtn');
        document.body.click();

        document.querySelector('#frontLabelInput').value = 'Question';
        document.querySelector('#backLabelInput').value = 'Answer';
        click('#saveLabelsBtn');
        assert(document.querySelector('#frontSegment').textContent === 'Question', 'Custom first-side name did not save');
        assert(document.querySelector('#backSegment').textContent === 'Answer', 'Custom second-side name did not save');

        document.querySelector('#frontInput').value = 'One';
        document.querySelector('#backInput').value = '1';
        document.querySelector('#addCardForm').requestSubmit();
        assert(state.sets[0].cards.length === 1, 'Manual card creation failed');
        assert(state.currentView === 'deck' && document.querySelector('#create').hidden, 'Saving a card did not return to Deck cards');
        assert(document.querySelectorAll('#homeStats .home-stat').length === 7, 'Home dashboard did not show all summary cards');
        assert(document.querySelector('[data-home-deck]'), 'Home dashboard did not show a recent deck');
        click('[data-home-deck]');
        assert(state.activeSetId === state.sets[0].id && state.queue.length === 1, 'Starting study from Home did not use the selected deck queue');

        click('[data-home-nav="library"]'); click('#fullLibraryGrid [data-set]'); click('#openAddCardsBtn');

        document.querySelector('#importInput').value = 'Two - 2\\nThree - 3';
        document.querySelector('#importFormat').value = 'hyphen';
        click('#importBtn');
        assert(!document.querySelector('#importPreviewDialog').hidden, 'Paste import did not open a preview');
        click('[data-import-action="confirm"]');
        assert(state.sets[0].cards.length === 3, 'Separator import failed');
        assert(getComputedStyle(document.querySelector('#emptyDeck')).display === 'none', 'Empty-deck panel is still visible after cards are added');
        assert(parseList('A\\n1\\nB\\n2', 'lines').length === 2, 'Two-line import preset failed');

        const one = state.sets[0].cards.find(card => card.front === 'One');
        click('[data-edit="' + one.id + '"]');
        document.querySelector('#editTagsInput').value = 'numbers, starter';
        document.querySelector('#editHintInput').value = 'The first counting word';
        document.querySelector('#editNotesInput').value = 'Useful starter context';
        document.querySelector('#cardEditorForm').requestSubmit();
        assert(state.sets[0].tags.includes('numbers') && !Object.hasOwn(one, 'tags') && one.hint && one.notes, 'Deck tags, hint, and notes did not save');
        state.sets[0].tags = ['Biology: Counting']; save(); render();
        click('#deckSubjectBtn');
        document.querySelector('#deckSubjectInput').value = 'Biology';
        document.querySelector('#deckDomainInput').value = 'science';
        document.querySelector('#deckMetadataForm').requestSubmit();
        assert(state.sets[0].primarySubject === 'Biology' && state.sets[0].domain === 'science', 'Deck subject details did not save');
        assert(state.sets[0].tags.includes('Biology: Counting'), 'Deck-level tag did not save');
        assert(state.sets[0].cards.every(card => !Object.hasOwn(card, 'tags')), 'Deck tags should not be copied to cards');
        click('#settingsBtn'); click('#subjectColoursBtn');
        const biologyColour = document.querySelector('[data-subject-colour-input="Biology"]');
        biologyColour.value = '#3c9a88'; biologyColour.dispatchEvent(new Event('input', { bubbles: true }));
        assert(state.subjectColors.Biology === '#3c9a88', 'Subject colour did not save');
        click('[data-subject-colour-action="close"]'); document.body.click();
        assert(document.querySelector('.set-entry').classList.contains('has-subject'), 'Subject library accent was not applied');
        assert(JSON.parse(localStorage.getItem(STORAGE_KEY)).subjectColors.Biology === '#3c9a88', 'Subject colours were not persisted');
        document.querySelector('#librarySort').value = 'subject'; document.querySelector('#librarySort').dispatchEvent(new Event('change', { bubbles: true }));
        assert(document.querySelector('#librarySort').value === 'subject', 'Subject library sort was not available');
        document.querySelector('#librarySort').value = 'manual'; document.querySelector('#librarySort').dispatchEvent(new Event('change', { bubbles: true }));
        document.querySelector('#deckSearch').value = 'starter context';
        document.querySelector('#deckSearch').dispatchEvent(new Event('input', { bubbles: true }));
        assert(document.querySelector('[data-edit="' + one.id + '"]'), 'Deck search did not find card notes');
        click('#clearSearchBtn');
        document.querySelector('#tagFilterOptions input[value="Biology: Counting"]').checked = true;
        document.querySelector('#tagFilterOptions').dispatchEvent(new Event('change', { bubbles: true }));
        assert(state.selectedTags.includes('Biology: Counting') && state.queue.length === state.sets[0].cards.length, 'Deck tag filter did not combine with study queue');
        state.selectedTags = []; buildQueue();
        click('#selectCardsBtn'); click('[data-select-card="' + one.id + '"]');
        window.prompt = () => 'practice'; click('#bulkTagBtn');
        assert(!Object.hasOwn(one, 'tags'), 'Bulk card tag controls should not add per-card tags');
        renameTag('Biology: Counting', 'review'); assert(state.sets[0].tags.includes('review'), 'Deck tag rename failed'); deleteTag('review'); assert(!state.sets[0].tags.includes('review'), 'Deck tag deletion failed');
        click('#bulkDuplicateBtn'); assert(state.sets[0].cards.length === 4, 'Bulk duplicate failed'); click('#selectCardsBtn');
        assert(findDuplicate({ front: ' one ', back: '1!!!' }) === one, 'Normalised duplicate detection failed');
        assert(parseDelimited('first_side,second_side,tags\\nA,B,"x, y"', ',')[1][2] === 'x, y', 'CSV parser failed quoted fields');
        assert(parseDelimited('first_side\\tsecond_side\\nA\\tB', '\\t').length === 2, 'TSV parser failed');
        openImportPreview([{ front: 'One', back: '1' }, { front: 'Four', back: '4', tags: ['numbers'] }]);
        document.querySelector('#importFlowDuplicates').value = 'skip'; click('[data-import-action="confirm"]');
        assert(state.sets[0].cards.some(card => card.front === 'Four') && state.sets[0].cards.filter(card => card.front === 'One').length === 2, 'Import preview duplicate decision failed');
        state.importDraft = rowsToImportDraft([['Word', 'Translation', 'Gender', 'Part of speech', 'Notes', 'Hint', 'Accepted alternatives', 'Tags'], ['Abiturfeier (f)', 'graduation day', '', 'noun', 'School event', 'Celebration', 'graduation ceremony', 'language, beginner']]);
        renderImportPreview();
        assert(document.querySelector('.import-flow') && document.querySelector('.import-card-table') && document.querySelector('[data-import-map="gender"]'), 'Three-stage import flow did not render its metadata, mapping, and card table controls');
        document.querySelector('#importFlowDestination').value = 'new'; document.querySelector('#importFlowDestination').dispatchEvent(new Event('change', { bubbles: true }));
        const setInput = (selector, value, type = 'input') => { const node = document.querySelector(selector); node.value = value; node.dispatchEvent(new Event(type, { bubbles: true })); };
        setInput('#importFlowDeckName', 'German nouns'); setInput('#importFlowSubject', 'German'); setInput('#importFlowDomain', 'language', 'change'); setInput('#importFlowLanguage', 'de', 'change'); setInput('#importFlowTags', 'language, beginner');
        click('[data-import-action="confirm"]');
        const germanDeck = state.sets.find(set => set.name === 'German nouns'); const importedNoun = germanDeck.cards[0];
        assert(germanDeck.domain === 'language' && germanDeck.language.code === 'de' && germanDeck.tags.includes('language') && !Object.hasOwn(importedNoun, 'tags'), 'New deck import metadata was not saved as deck-level data');
        assert(importedNoun.front === 'Abiturfeier' && importedNoun.wordInfo.gender === 'feminine' && importedNoun.wordInfo.originalMarker === '(f)' && importedNoun.wordInfo.partOfSpeech === 'noun', 'Import did not preserve detected word metadata');
        openSharePreview({ format: 'recall-share-v1', folders: [{ id: 'source-folder', name: 'Shared folder', color: '#2447c2' }], sets: [{ id: 'source-set', name: 'Shared set', folderId: 'source-folder', frontLabel: 'Question', backLabel: 'Answer', cards: [{ front: 'Shared', back: 'Card', tags: ['shared'] }] }] });
        click('[data-import-action="confirm"]');
        assert(state.sets.some(set => set.name === 'Shared set') && state.folders.some(folder => folder.name === 'Shared folder'), 'Shared multi-deck import did not preserve deck and folder data');
        click('[data-home-nav="test"]');
        assert(!document.querySelector('#testMode').hidden, 'Test mode setup did not open');
        document.querySelector('#testQuestionCount').value = '2';
        document.querySelector('#testAnswerStyle').value = 'typed';
        click('[data-test-action="start"]');
        assert(state.activeTest && state.activeTest.questions.length === 2, 'Test mode did not select a unique question set');
        assert(state.activeTest.questions.every(question => question.subject === 'Biology'), 'Test questions lost their subject for AI guidance');
        await wait(0);
        assert(document.activeElement?.id === 'testTypedInput', 'Typed Test Mode answer field did not receive focus');
        document.querySelector('#testTypedInput').value = testAnswerValue(activeTestQuestion());
        document.querySelector('#testTypedForm').requestSubmit();
        assert(state.activeTest.feedback.result === 'correct', 'Typed test answer did not use forgiving matching');
        click('[data-test-action="next"]');
        await wait(0);
        assert(document.activeElement?.id === 'testTypedInput', 'Next typed Test Mode question did not refocus the answer field');
        click('[data-test-action="skip"]');
        assert(!state.activeTest && state.testHistory.length === 1, 'Completed test was not saved separately');
        assert(document.querySelector('#testMode').textContent.includes('Review every question'), 'Test results screen did not render complete question review');
        click('[data-test-action="history"]');
        assert(document.querySelector('.test-history-list'), 'Dedicated test history did not open');
        assert(document.querySelector('[data-test-action="open-saved"]'), 'Saved test was missing from history');
        click('[data-test-action="open-saved"]');
        click('[data-test-review-filter="correct"]');
        assert(document.querySelector('#testMode').textContent.includes('Correct'), 'Test result filters did not work');
        click('[data-test-action="history"]');
        window.confirm = () => true; click('[data-test-action="delete-test"]');
        assert(state.testHistory.length === 0, 'Saved test deletion failed');
        window.confirm = () => false;
        click('[data-test-action="close"]');
        click('[data-home-nav="test"]');
        document.querySelector('#testQuestionCount').value = '1';
        click('[data-test-action="start"]');
        state.activeTest.deadlineAt = new Date(Date.now() - 1).toISOString();
        updateTestTimer();
        assert(!state.activeTest && state.testHistory.at(-1).finishReason === 'time-expired', 'Timed test did not finish when its countdown expired');
        click('[data-test-action="close"]');

        state.shuffled = false; buildQueue(); click('#revealHintBtn');
        assert(document.querySelector('#hintText').textContent === 'The first counting word', 'Study hint did not reveal without flipping the card');

        const firstText = document.querySelector('#cardContent').textContent;
        click('#flashcard');
        assert(document.querySelector('#cardContent').textContent !== firstText, 'Card flip failed');

        click('#sessionMenuBtn');
        document.querySelector('#sessionShuffle').checked = false;
        document.querySelector('#repeatMissed').checked = true;
        click('#applySessionBtn');
        assert(!state.shuffled && state.repeatMissed, 'Session options were not applied');
        const beforeRetry = state.queue.length;
        click('#retryBtn');
        await wait(300);
        assert(state.queue.length === beforeRetry + 1, 'Repeat-missed option did not queue the card');
        assert(state.retry === 1, 'Retry score did not update');
        assert(state.reviewLog.length === 1 && state.reviewLog[0].outcome === 'retry', 'Retry review event was not recorded');
        const retriedCard = state.sets.flatMap(set => set.cards).find(card => card.id === state.reviewLog[0].cardId);
        assert(state.reviewLog[0].responseTimeMs >= 0 && retriedCard.lastReviewedAt && new Date(retriedCard.dueAt) > new Date(retriedCard.lastReviewedAt), 'Scheduling metadata was not recorded');
        click('#undoBtn');
        assert(state.retry === 0 && state.queue.length === beforeRetry, 'Undo did not restore the session');
        assert(state.reviewLog.length === 0, 'Undo did not remove the review event');

        click('#correctBtn');
        await wait(300);
        assert(state.correct === 1, 'Correct review did not update score');
        assert(state.currentSession.attempts === 1, 'Current session history did not update');
        assert(one.state === 'Learning' && one.correctStreak === 1, 'A reviewed new card did not become Learning');
        assert(one.lastReviewedAt && new Date(one.dueAt) > new Date(one.lastReviewedAt), 'Successful review did not schedule the card forward');
        assert(JSON.parse(localStorage.getItem(STORAGE_KEY)).reviewLog.length === 1, 'Review log was not persisted');
        assert(normaliseCard({ front: 'Legacy', back: 'card' }).state === 'New', 'Existing cards do not migrate to the New state');
        state.shuffled = false; state.studyFilter = 'all'; buildQueue();
        click('#correctBtn'); await wait(300);
        assert(one.state === 'Learning' && one.correctStreak === 2 && one.fsrs.scheduled_days < 7, 'Two immediate correct answers incorrectly mastered a card');
        assert(state.currentSession.learned === 0, 'A short review interval incorrectly incremented learned activity');
        one.lastReviewedAt = one.fsrs.last_review = new Date(Date.now() - 2 * 86400000).toISOString();
        one.dueAt = one.fsrs.due = new Date(Date.now() - 1000).toISOString();
        const beforeMastery = structuredClone(one);
        buildQueue(); click('#correctBtn'); await wait(300);
        assert(one.state === 'Mastered' && one.fsrs.scheduled_days >= 7 && state.currentSession.learned === 1, 'A spaced correct answer did not earn mastery at a seven-day interval');
        click('#undoBtn');
        assert(JSON.stringify(one) === JSON.stringify(beforeMastery) && state.currentSession.learned === 0, 'Undo did not restore the card and mastery activity');
        click('#correctBtn'); await wait(300);
        const masteredMemory = structuredClone(one.fsrs);
        buildQueue(); click('#retryBtn'); await wait(300);
        assert(one.state === 'Learning' && one.missed && one.correctStreak === 0, 'Incorrect answer did not return card to Learning and mark it missed');
        assert(one.fsrs.reps === masteredMemory.reps + 1 && one.fsrs.lapses === masteredMemory.lapses + 1 && one.fsrs.stability > 0, 'A mastery lapse reset FSRS memory');
        state.studyFilter = 'missed'; buildQueue();
        assert(state.queue.length === 1 && state.queue[0].id === one.id, 'Missed-card study filter did not limit the session');
        click('#flagBtn'); assert(one.flagged, 'Flagging a card failed');
        state.studyFilter = 'flagged'; buildQueue();
        assert(state.queue.length === 1 && state.queue[0].id === one.id, 'Flagged-card study filter did not limit the session');
        state.studyFilter = 'new'; buildQueue();
        assert(state.queue.every(card => card.state === 'New'), 'New-card study filter included a reviewed card');
        state.studyFilter = 'learning'; buildQueue();
        assert(state.queue.every(card => card.state === 'Learning'), 'Learning-card study filter did not work');
        state.studyFilter = 'due'; buildQueue();
        assert(state.queue.every(card => RecallScheduler.isDue(card)), 'Due-card study filter included a future card');
        state.studyFilter = 'all'; state.studyMode = 'typed'; state.startSide = 'back'; buildQueue();
        document.querySelector('#typedAnswerInput').value = '  one!!! ';
        document.querySelector('#typedAnswerForm').requestSubmit();
        assert(state.typedChecked && state.typedChecked.accepted, 'Typed answer did not accept case and punctuation variations');
        document.querySelector('#typedAnswerForm').requestSubmit(); await wait(300);
        assert(state.currentSession.mode === 'typed' && state.correct === 1, 'Typed answer mode did not record a successful review');
        assert(answersMatch('Abiturfeier', 'Abiturfeier (f)'), 'Bracketed expected text was not optional');
        assert(!answersMatch('Abitur', 'Abiturfeier (f)'), 'Genuinely different typed answer was accepted');
        const activity = state.activity[localDayKey()];
        assert(activity && activity.reviewed > 0 && Object.values(activity.decks).some(deck => deck.name === state.sets[0].name), 'Study activity was not persisted per day and deck');
        assert(studyStreaks().current >= 1 && studyStreaks().longest >= 1, 'Study streak calculation failed');
        assert(document.querySelectorAll('.heatmap-day').length === 112, 'Calendar heatmap did not render all days');
        assert(document.querySelector('#progressChart polyline'), 'Progress chart did not render');
        click('#attemptsTrigger');
        assert(document.querySelector('#attemptsDrawer').classList.contains('open') && document.querySelector('.attempt-entry'), 'Deck attempt history did not open');
        click('#attemptsClose');

        // Completion dialog: its missed-card actions use only this session's retry IDs.
        state.studyMode = 'flip'; state.repeatMissed = false; state.shuffled = false;
        resetStudyRun([one], 'all');
        const historyBeforeCompletion = state.sessionHistory.length;
        click('#retryBtn'); await wait(300);
        assert(!completionDialog.hidden, 'Completion popup did not appear when the queue finished');
        assert(completionDialog.textContent.includes('Reviewed') && completionDialog.textContent.includes('1') && completionDialog.textContent.includes('To revisit'), 'Completion popup summary was incorrect');
        assert(completionDialog.querySelector('[data-completion-action="practice"]') && completionDialog.querySelector('[data-completion-action="test"]'), 'Missed-card actions were hidden after a retry');
        click('[data-completion-action="test"]');
        assert(!testMode.hidden && cardsForTest(testSetupConfig()).length === 1 && cardsForTest(testSetupConfig())[0].id === one.id, 'Test missed cards did not limit Test Mode to the session misses');
        assert(state.sessionHistory.length === historyBeforeCompletion + 1, 'Opening Test Mode did not finish the completed session exactly once');
        closeTestMode(); state.pendingTestCardIds = null;

        resetStudyRun([one], 'all');
        click('#retryBtn'); await wait(300);
        click('[data-completion-action="practice"]');
        assert(state.queue.length === 1 && state.queue[0].id === one.id && state.currentSession.filter === 'session-missed', 'Practice missed cards did not start an isolated missed-card queue');
        click('#correctBtn'); await wait(300);
        assert(!completionDialog.hidden, 'Completion popup did not reopen after practicing missed cards');
        assert(!completionDialog.querySelector('[data-completion-action="practice"]') && !completionDialog.querySelector('[data-completion-action="test"]'), 'Missed-card actions remained visible with no retries');
        document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
        assert(completionDialog.hidden && document.querySelector('#cardPosition').textContent === 'SESSION COMPLETE', 'Escape did not close the completion popup and keep the fallback state');
        openCompletionDialog(); click('[data-completion-action="close"]');
        assert(completionDialog.hidden, 'Close action did not dismiss the completion popup');
        const restartExpected = cardsForStudy().length;
        openCompletionDialog(); click('[data-completion-action="restart"]');
        assert(state.queue.length === restartExpected && state.currentIndex === 0, 'Restart deck did not rebuild the active deck with current session settings');

        const secondCard = state.sets[0].cards.find(card => card.id !== one.id);
        resetStudyRun([one, secondCard], 'all');
        click('#correctBtn'); await wait(300);
        click('#correctBtn'); await wait(300);
        click('[data-completion-action="close"]');
        document.dispatchEvent(new KeyboardEvent('keydown', { key: 'z', bubbles: true }));
        assert(state.currentIndex === 1 && state.correct === 1 && state.history.length === 1, 'One Z keypress undid more than one card');
        document.dispatchEvent(new KeyboardEvent('keydown', { key: 'z', repeat: true, bubbles: true }));
        assert(state.currentIndex === 1 && state.correct === 1, 'Holding Z repeated the undo action');
        document.dispatchEvent(new KeyboardEvent('keydown', { key: 'w', bubbles: true }));
        assert(state.flipped, 'W did not flip the card once');
        document.dispatchEvent(new KeyboardEvent('keydown', { key: 'w', repeat: true, bubbles: true }));
        assert(state.flipped, 'Holding W flipped the card twice');
        document.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true }));
        assert(!state.flipped, 'ArrowDown did not flip the card once');

        click('#fullscreenBtn');
        await wait(80);
        assert(document.body.classList.contains('focus-study'), 'Fullscreen focus layout did not open');
        click('#exitFocusBtn');
        await wait(80);
        assert(!document.body.classList.contains('focus-study'), 'Fullscreen focus layout did not close');

        click('[data-home-nav="library"]');
        click('#newSetBtn');
        assert(!document.querySelector('#libraryDialog').hidden, 'Add Set dialog did not open');
        document.querySelector('#libraryDialogInput').value = 'Biology';
        click('#libraryDialogSave');
        assert(document.querySelector('#libraryDialog').hidden && getComputedStyle(document.querySelector('#libraryDialog')).display === 'none' && state.sets.some(set => set.name === 'Biology'), 'Add Set did not save and visibly close');
        const biology = state.sets.find(item => item.name === 'Biology');
        click('[data-rename-set="' + biology.id + '"]');
        document.querySelector('#libraryDialogInput').value = 'Life Science';
        click('#libraryDialogSave');
        assert(biology.name === 'Life Science', 'Set rename failed');

        click('#newFolderBtn');
        document.querySelector('#libraryDialogInput').value = 'Science';
        click('#libraryDialogSave');
        assert(state.folders.some(folder => folder.name === 'Science'), 'Add Folder did not save');
        const folder = state.folders.find(item => item.name === 'Science');
        click('[data-rename-folder="' + folder.id + '"]');
        document.querySelector('#libraryDialogInput').value = 'STEM';
        click('#libraryDialogSave');
        assert(folder.name === 'STEM', 'Folder rename failed');
        moveSetToFolder(biology.id, folder.id);
        assert(biology.folderId === folder.id, 'Moving a set into a folder failed');

        const colour = document.querySelector('[data-folder-color="' + folder.id + '"]');
        colour.value = '#bc5b55';
        colour.dispatchEvent(new Event('change', { bubbles: true }));
        assert(folder.color === '#bc5b55', 'Folder colour did not save');

        click('#newSetBtn');
        document.querySelector('#libraryDialogInput').value = 'Chemistry';
        click('#libraryDialogSave');
        const chemistry = state.sets.find(item => item.name === 'Chemistry');
        const chemistrySiblings = state.sets.filter(item => item.folderId === chemistry.folderId).sort((a, b) => a.order - b.order);
        const precedingSet = chemistrySiblings[chemistrySiblings.indexOf(chemistry) - 1];
        click('[data-move-set="' + chemistry.id + '"][data-direction="up"]');
        assert(precedingSet && chemistry.order < precedingSet.order, 'Manual set reordering failed');

        click('#newFolderBtn');
        document.querySelector('#libraryDialogInput').value = 'Languages';
        click('#libraryDialogSave');
        const languages = state.folders.find(item => item.name === 'Languages');
        click('[data-move-folder="' + languages.id + '"][data-direction="up"]');
        assert(languages.order < folder.order, 'Manual folder reordering failed');

        click('[data-toggle-folder="' + folder.id + '"]');
        assert(folder.collapsed, 'Folder collapse failed');
        click('[data-toggle-folder="' + folder.id + '"]');
        assert(!folder.collapsed, 'Folder expand failed');
        click('#fullLibraryBtn');
        assert(!document.querySelector('#fullLibrary').hidden && document.querySelector('.deck-grid-card'), 'Full library grid did not open');
        click('#fullLibraryClose');

        document.querySelector('#librarySearch').value = 'life';
        document.querySelector('#librarySearch').dispatchEvent(new Event('input', { bubbles: true }));
        assert(document.querySelector('[data-set="' + biology.id + '"]'), 'Library filtering failed');
        document.querySelector('#librarySort').value = 'name-asc';
        document.querySelector('#librarySort').dispatchEvent(new Event('change', { bubbles: true }));
        deleteSet(chemistry.id);
        assert(!state.sets.some(set => set.id === chemistry.id), 'Deck deletion failed');
        deleteFolder(languages.id);
        assert(!state.folders.some(item => item.id === languages.id), 'Folder deletion failed');

        click('[data-home-nav="library"]');
        click('#sharedWithMeBtn');
        assert(document.querySelector('#deckShareDialog').open && document.querySelector('#shareSavedLinks'), 'Shared with me did not open');
        click('#deckShareDialog [data-share-action="close"]');
        click('#fullLibraryGrid [data-share-set="' + biology.id + '"]');
        assert(document.querySelector('#deckShareDialog').open && document.querySelector('#shareOwnerName').textContent === 'Life Science', 'Deck share action did not target the chosen deck');
        click('#deckShareDialog [data-share-action="close"]');
        const sharedCopy = window.RecallLibrary.addSharedDeck(window.RecallShareCore.snapshotDeck(state.sets[0]));
        assert(sharedCopy.id !== state.sets[0].id && state.currentView === 'deck', 'Copy to my library did not create a separate deck');
        assert(sharedCopy.cards.every(card => card.state === 'New' && card.reviewCount === 0 && !card.notes && !card.hint), 'Shared copy retained private fields or review progress');

        const hostileId = 'id"><img src=x onerror=alert(1)>';
        sharedCopy.cards.push(normaliseCard({ id: hostileId, front: '<img src=x onerror=alert(1)>', back: 'safe', notes: '<script>alert(1)</script>' }));
        renderDeck();
        assert(!document.querySelector('#deckList img, #deckList script, #deckList [onerror]'), 'Card rendering interpreted untrusted HTML');
        assert([...document.querySelectorAll('#deckList [data-edit]')].some(button => button.dataset.edit === hostileId), 'Escaped card ID lost its value');
        sharedCopy.cards.pop();
        const hostileFolder = { id: hostileId, name: '<img src=x>', color: 'red; background:url(https://evil.example)', order: 999 };
        state.folders.push(hostileFolder); renderLibrary(); renderFullLibrary();
        assert(!document.querySelector('#libraryTree img, #fullLibraryGrid img, #libraryTree [onerror]'), 'Library rendering interpreted untrusted HTML');
        assert(document.querySelector('#libraryTree [data-folder-color]') && !document.querySelector('#libraryTree [style*="evil.example"]'), 'Unsafe folder colour reached CSS');
        state.folders.pop();
        assert(typeof openSharePreview === 'function', 'Share-file validation is unavailable');
        let rejectedShare = false;
        try { openSharePreview({ format: 'recall-share-v2', sets: [{ name: 'Bad', cards: Array(2001).fill({ front: 'a', back: 'b' }) }] }); } catch { rejectedShare = true; }
        assert(rejectedShare, 'Oversized share file was accepted');
        assert(csvEscape('=HYPERLINK("https://evil.example")', ',').replace(/^"/, '').startsWith("'"), 'CSV export did not neutralise spreadsheet formulas');

        const previousCloud = window.RecallCloudClient;
        const previousAI = state.aiEnabled;
        let aiCalls = 0;
        const aiReplies = [
          { result: 'correct', score: 95, feedback: 'The meaning is equivalent.', missing_points: [], confidence: 0.9 },
          { result: 'partially_correct', score: 55, feedback: 'One key idea is missing.', missing_points: ['membrane'], confidence: 0.8 },
          { result: 'incorrect', score: 0, feedback: 'This does not match.', missing_points: [], confidence: 0.9 },
        ];
        window.RecallCloudClient = { enabled: true, create: () => ({
          auth: { getSession: async () => ({ data: { session: { access_token: 'test-session' } } }) },
          functions: { invoke: async (name, options) => { aiCalls++; assert(name === 'evaluate-answer' && Object.keys(options.body).length === 7, 'Appeal did not use the allowlisted Edge Function request'); return { data: aiReplies.shift(), error: null }; } },
        }) };
        state.aiEnabled = false; aiToggle.checked = false; localStorage.setItem('recall-ai-enabled-v1', 'false');
        state.activeSetId = state.sets[0].id; state.studyMode = 'typed'; state.startSide = 'front'; state.shuffled = false;
        resetStudyRun([one], 'all');
        document.querySelector('#typedAnswerInput').value = 'different meaning';
        document.querySelector('#typedAnswerForm').requestSubmit();
        assert(state.typedChecked.originalResult === 'incorrect' && aiCalls === 0 && document.querySelector('#typedAppeal [data-appeal-answer]'), 'Local result did not precede optional appeal');
        click('#typedAppeal [data-appeal-answer]');
        assert(state.aiEnabled && aiToggle.checked && localStorage.getItem('recall-ai-enabled-v1') === 'true' && document.querySelector('#typedAppeal').textContent.includes('Checking appeal'), 'First appeal click did not enable AI and show progress');
        await wait(20);
        assert(state.typedChecked.result === 'correct' && state.typedChecked.originalResult === 'incorrect' && document.querySelector('#typedAppeal').textContent.includes('Appeal accepted') && aiCalls === 1, 'Accepted appeal did not preserve local result and grant correct credit: ' + JSON.stringify({ checked: state.typedChecked, calls: aiCalls, text: document.querySelector('#typedAppeal').textContent }));
        assert(!document.querySelector('#typedAppeal [data-appeal-answer]'), 'An answer could be appealed twice');
        document.querySelector('#typedAnswerForm').requestSubmit(); await wait(300);
        assert(state.reviewLog.at(-1).outcome === 'correct' && state.reviewLog.at(-1).answerResult === 'correct', 'Accepted appeal did not schedule as correct');
        undoReview();
        document.querySelector('#typedAnswerInput').value = 'different meaning'; document.querySelector('#typedAnswerForm').requestSubmit();
        click('#typedAppeal [data-appeal-answer]');
        assert(aiCalls === 1 && document.querySelector('#typedAppeal').textContent.includes('already appealed'), 'Undo allowed a repeated appeal for the same answer');
        closeCompletionDialog();
        resetStudyRun([one], 'all');
        document.querySelector('#typedAnswerInput').value = 'another wrong meaning';
        document.querySelector('#typedAnswerForm').requestSubmit(); click('#typedAppeal [data-appeal-answer]'); await wait(20);
        assert(state.typedChecked.result === 'partially_correct' && !state.typedChecked.accepted && document.querySelector('#typedAppeal').textContent.includes('Appeal partially accepted'), 'Partial appeal became full credit');
        document.querySelector('#typedAnswerForm').requestSubmit(); await wait(300);
        assert(state.reviewLog.at(-1).outcome === 'retry' && state.reviewLog.at(-1).answerResult === 'partially_correct' && state.currentSession.partialPoints === .55, 'Partial appeal did not preserve a due review and fractional credit');
        assert(document.querySelector('#sessionScore').textContent === '55%' && document.querySelector('#completionDialog').textContent.includes('Partial'), 'Partial study credit did not reach the session summary');
        click('[data-home-nav="test"]'); document.querySelector('#testQuestionCount').value = '1'; document.querySelector('#testAnswerStyle').value = 'typed'; click('[data-test-action="start"]');
        document.querySelector('#testTypedInput').value = 'unrelated answer'; document.querySelector('#testTypedForm').requestSubmit();
        assert(state.activeTest.feedback.originalResult === 'incorrect' && aiCalls === 2 && document.querySelector('[data-test-appeal]'), 'Test Mode called AI before appeal');
        state.aiEnabled = false; aiToggle.checked = false; localStorage.setItem('recall-ai-enabled-v1', 'false');
        click('[data-test-appeal]'); await wait(20);
        assert(state.aiEnabled && aiToggle.checked && state.activeTest.feedback.result === 'incorrect' && document.querySelector('.test-appeal').textContent.includes('Appeal rejected') && aiCalls === 3, 'Test Mode appeal did not start from the button or changed the local grade');
        window.RecallCloudClient = previousCloud; state.aiEnabled = previousAI; aiToggle.checked = previousAI; localStorage.setItem('recall-ai-enabled-v1', String(previousAI));
        closeTestMode(); setAppView('deck'); resetStudyRun([one], 'all');
        document.querySelector('#typedAnswerInput').value = 'offline answer'; document.querySelector('#typedAnswerForm').requestSubmit();
        click('#typedAppeal [data-appeal-answer]'); await wait(20);
        assert(state.typedChecked.originalResult === 'incorrect' && document.querySelector('#typedAppeal').textContent.includes('Cloud connection is not configured') && aiCalls === 3, 'Offline appeal did not explain why the local result was kept');
        window.RecallCloudClient = { enabled: true, create: () => ({ auth: { getSession: async () => ({ data: { session: null } }) }, functions: { invoke: async () => { throw new Error('Signed-out appeal reached the server'); } } }) };
        resetStudyRun([one], 'all'); document.querySelector('#typedAnswerInput').value = 'signed out answer'; document.querySelector('#typedAnswerForm').requestSubmit();
        click('#typedAppeal [data-appeal-answer]'); await wait(20);
        assert(state.typedChecked.originalResult === 'incorrect' && document.querySelector('#typedAppeal').textContent.includes('Sign in to appeal'), 'Signed-out appeal did not show an inline sign-in message');
        window.RecallCloudClient = previousCloud; state.aiEnabled = previousAI; aiToggle.checked = previousAI; localStorage.setItem('recall-ai-enabled-v1', String(previousAI));

        click('[data-home-nav="library"]'); click('#browseCatalogBtn');
        assert(!document.querySelector('#catalogLibrary').hidden && document.querySelectorAll('.catalog-card').length === RecallCatalogData.entries.length, 'Built-in library did not open with all bundled decks');
        assert([...document.querySelectorAll('#catalogGrid .catalog-subject-group h2')].map(heading => heading.textContent).join('|') === 'Biology|Chemistry|Physics', 'Catalog decks were not grouped by subject');
        const chemistryGroup = [...document.querySelectorAll('#catalogGrid .catalog-subject-group')].find(group => group.querySelector('h2')?.textContent === 'Chemistry');
        const chemistryEntries = RecallCatalogData.entries.filter(entry => entry.subject === 'Chemistry');
        assert(chemistryGroup.querySelectorAll('.catalog-topic-group').length === new Set(chemistryEntries.map(entry => entry.topic)).size && chemistryGroup.querySelectorAll('.catalog-card').length === chemistryEntries.length, 'Chemistry decks were not grouped by topic');
        assert(!chemistryGroup.querySelector('.catalog-topic-group > h3') && chemistryGroup.querySelectorAll('.catalog-card h3').length === chemistryEntries.length, 'Topic title was duplicated above a deck box');
        const chemistryTopics = chemistryGroup.querySelectorAll('.catalog-card');
        const firstTopic = chemistryTopics[0].getBoundingClientRect(); const secondTopic = chemistryTopics[1].getBoundingClientRect();
        assert(Math.abs(firstTopic.top - secondTopic.top) < 1 && secondTopic.left > firstTopic.left, 'Multiple topics in one subject were stacked instead of shown in a grid');
        document.querySelector('#catalogQualification').value = 'GCSE'; document.querySelector('#catalogQualification').dispatchEvent(new Event('change'));
        document.querySelector('#catalogBoard').value = 'AQA'; document.querySelector('#catalogBoard').dispatchEvent(new Event('change'));
        const catalogFixture = RecallCatalogData.entries.find(entry => entry.id === 'gcse-aqa-physics-4611-transverse-longitudinal');
        document.querySelector('#catalogSubtopic').value = catalogFixture.subtopic; document.querySelector('#catalogSubtopic').dispatchEvent(new Event('change'));
        document.querySelector('#catalogSearch').value = 'Waves'; document.querySelector('#catalogSearch').dispatchEvent(new Event('input'));
        assert(document.querySelectorAll('.catalog-card').length === 1, 'Catalog search and qualification/board filters failed');
        assert(document.querySelectorAll('#catalogGrid .catalog-subject-group').length === 1 && document.querySelector('#catalogGrid .catalog-subject-group h2').textContent === 'Physics', 'Filtering left unrelated subject groups visible');
        document.querySelector('#catalogSearch').value = 'no matching deck'; document.querySelector('#catalogSearch').dispatchEvent(new Event('input'));
        assert(!document.querySelector('#catalogGrid .catalog-subject-group') && document.querySelector('#catalogGrid .library-empty'), 'Empty catalog search left stale groups visible');
        document.querySelector('#catalogSearch').value = 'Waves'; document.querySelector('#catalogSearch').dispatchEvent(new Event('input'));
        click('[data-catalog-id="' + catalogFixture.id + '"]');
        assert(!document.querySelector('#catalogPreview').hidden && document.querySelectorAll('#catalogPreviewCards article').length === Math.min(20, catalogFixture.cardCount), 'Catalog preview did not show source cards');
        const originalCatalogFront = window.RecallCatalogData.entries[0].cards[0].front;
        const deckCountBeforeCatalog = state.sets.length;
        click('#catalogAdd');
        const catalogCopy = state.sets.at(-1);
        assert(state.sets.length === deckCountBeforeCatalog + 1 && catalogCopy.cards.length === catalogFixture.cardCount && state.currentView === 'deck', 'Catalog copy did not add a new editable deck');
        assert(catalogCopy.cards.every(card => card.state === 'New' && card.reviewCount === 0) && document.querySelector('#catalogLibrary').hidden, 'Catalog copy retained study progress or left the catalog open');
        catalogCopy.cards[0].front = 'Personal edit';
        assert(window.RecallCatalogData.entries[0].cards[0].front === originalCatalogFront, 'Editing the copied deck changed the catalog source');

        const copyId = catalogCopy.id;
        click('#deckStartReviewBtn');
        assert(state.currentView === 'review' && state.dailyReview.queue.length === catalogFixture.cardCount, 'Deck review did not queue the copied library cards');
        assert(document.querySelector('#dailyReviewAnswer').hidden && document.querySelector('#dailyRatingButtons').hidden, 'Daily review revealed the answer before the user chose to');
        click('#revealReviewBtn');
        assert(!document.querySelector('#dailyReviewAnswer').hidden && !document.querySelector('#dailyRatingButtons').hidden, 'Reveal did not show answer and rating intervals');
        assert([...document.querySelectorAll('#dailyRatingButtons small')].every(item => item.textContent), 'Predicted rating intervals were missing');
        click('[data-review-rating="Good"]');
        assert(state.dailyReview.index === 1 && state.dailyReview.ratings.Good === 1, 'Good rating did not advance the daily review');
        assert(JSON.parse(localStorage.getItem(STORAGE_KEY)).dailyReview.index === 1, 'Daily review progress was not persisted');
        assert(catalogCopy.cards.some(card => card.reviewCount === 1 && card.fsrs?.stability > 0), 'FSRS scheduling was not saved on the copied card');
        assert(window.RecallCatalogData.entries[0].cards[0].front === originalCatalogFront, 'Review changed static library content');
        click('#leaveReviewBtn');
        load();
        startDailyReview({ deckId: copyId });
        assert(state.dailyReview.index === 1 && document.querySelector('#dailyReviewAnswer').hidden, 'Interrupted review did not resume safely with answer hidden');
        for (const rating of ['Again', 'Hard', 'Easy', ...Array(catalogFixture.cardCount - 4).fill('Good')]) {
          click('#revealReviewBtn');
          click('[data-review-rating="' + rating + '"]');
        }
        assert(state.dailyReview.index === catalogFixture.cardCount && !document.querySelector('#dailyReviewSummary').hidden, 'Completed daily review did not show a session summary');
        assert(state.dailyReview.ratings.Again === 1 && state.dailyReview.ratings.Hard === 1 && state.dailyReview.ratings.Good === catalogFixture.cardCount - 3 && state.dailyReview.ratings.Easy === 1, 'Four-way rating counts were incorrect');
        assert(document.querySelector('#dailyReviewSummary').textContent.includes(catalogFixture.cardCount + ' cards reviewed') && document.querySelector('#dailyReviewSummary').textContent.includes('Approximate recall'), 'Session summary omitted review count or recall');

        const masteryDeck = normaliseDeck({ id: makeId(), name: 'Mastery checks', cards: [
          { front: 'Spaced recall', back: 'Seven days' }, { front: 'Easy recall', back: 'Seven days' },
        ] });
        state.sets.push(masteryDeck);
        const [spacedCard, easyCard] = masteryDeck.cards;
        const rateMasteryCard = (card, rating) => {
          card.dueAt = card.fsrs.due = new Date(Date.now() - 1000).toISOString();
          startDailyReview({ deckId: masteryDeck.id });
          assert(currentDailyItem().card.id === card.id, 'Mastery check queued the wrong card');
          click('#revealReviewBtn'); click('[data-review-rating="' + rating + '"]');
        };
        // Control queue order without changing the real FSRS rating calculations.
        state.dailyReview = { id: makeId(), scope: { deckId: masteryDeck.id }, queue: masteryDeck.cards.map(card => ({ deckId: masteryDeck.id, cardId: card.id })), index: 0, timeSpentMs: 0, ratings: { Again: 0, Hard: 0, Good: 0, Easy: 0 } };
        startDailyReview({ deckId: masteryDeck.id });
        click('#revealReviewBtn'); click('[data-review-rating="Good"]');
        assert(spacedCard.state === 'Learning' && spacedCard.fsrs.scheduled_days < 7, 'Daily first Good rating incorrectly mastered the card');
        click('#revealReviewBtn'); click('[data-review-rating="Easy"]');
        assert(easyCard.state === 'Mastered' && easyCard.fsrs.scheduled_days >= 7, 'Daily Easy rating did not award a qualifying mastery interval');
        rateMasteryCard(spacedCard, 'Good');
        assert(spacedCard.fsrs.state === 2 && spacedCard.state === 'Learning', 'Daily Review confused FSRS Review state with mastery');
        spacedCard.lastReviewedAt = spacedCard.fsrs.last_review = new Date(Date.now() - 2 * 86400000).toISOString();
        rateMasteryCard(spacedCard, 'Good');
        assert(spacedCard.state === 'Mastered' && spacedCard.fsrs.scheduled_days >= 7, 'Daily spaced review did not earn mastery');
        const beforeDailyLapse = structuredClone(spacedCard.fsrs);
        rateMasteryCard(spacedCard, 'Again');
        assert(spacedCard.state === 'Learning' && spacedCard.missed && spacedCard.correctStreak === 0, 'Daily Again rating did not demote mastery');
        assert(spacedCard.fsrs.reps === beforeDailyLapse.reps + 1 && spacedCard.fsrs.lapses === beforeDailyLapse.lapses + 1 && spacedCard.fsrs.stability > 0, 'Daily lapse reset accumulated FSRS memory');
        for (let i = 0; i < 10 && spacedCard.state !== 'Mastered'; i += 1) {
          spacedCard.lastReviewedAt = spacedCard.fsrs.last_review = new Date(Date.now() - Math.max(1, spacedCard.fsrs.scheduled_days) * 86400000).toISOString();
          rateMasteryCard(spacedCard, 'Good');
        }
        assert(spacedCard.state === 'Mastered' && !spacedCard.missed && spacedCard.fsrs.lapses === beforeDailyLapse.lapses + 1, 'Daily successful reviews did not recover mastery while retaining lapse history');
        spacedCard.fsrs.scheduled_days = 6;
        easyCard.fsrs.scheduled_days = 7;
        const savedSpacedCard = structuredClone(spacedCard);
        save(); load();
        const restoredMastery = state.sets.find(deck => deck.id === masteryDeck.id);
        assert(restoredMastery.cards[0].state === 'Learning' && restoredMastery.cards[1].state === 'Mastered', 'Loading did not reevaluate existing mastery at the seven-day boundary');
        assert(JSON.stringify(restoredMastery.cards[0].fsrs) === JSON.stringify(savedSpacedCard.fsrs) && restoredMastery.cards[0].reviewCount === savedSpacedCard.reviewCount, 'Loading reset existing scheduling or review counts');

        return 'All automated feature checks passed.';
      })();
    `);
    console.log(result);
  } catch (error) {
    console.error(error.stack || error);
    process.exitCode = 1;
  } finally {
    window.destroy();
    app.exit(process.exitCode || 0);
  }
});
