const test = require('node:test');
const assert = require('node:assert/strict');
const { parseSubjectTag, subjectsForCards, subjectsForDeck, primarySubject, colourForSubject, accentForDeck, saveColours, loadColours } = require('./subject-utils');
test('parses Subject: Topic tags while preserving ordinary tags', () => { assert.deepEqual(parseSubjectTag('Biology: Transpiration'), { subject: 'Biology', topic: 'Transpiration' }); assert.equal(parseSubjectTag('important'), null); assert.equal(parseSubjectTag('German:'), null); });
test('detects distinct subjects represented by deck card tags', () => { const cards = [{ tags: ['Biology: Cells', 'exam'] }, { tags: ['German: Family', 'Biology: Photosynthesis'] }]; assert.deepEqual(subjectsForCards(cards), ['Biology', 'German']); });
test('deck-level subject tags work without copying tags onto every card', () => { assert.deepEqual(subjectsForDeck({ tags: ['Maths: Quadratics', 'exam'], cards: [{ tags: ['important'] }] }), ['Maths']); });
test('uses manual primary subject and falls back safely when it disappears', () => { const deck = { primarySubject: 'German', cards: [{ tags: ['Biology: Cells'] }] }; assert.deepEqual(primarySubject(deck), { subject: 'Biology', fallback: true }); deck.primarySubject = 'Biology'; assert.deepEqual(primarySubject(deck), { subject: 'Biology', fallback: false }); });
test('subject colours are stable, customisable, and drive deck accents', () => { const deck = { primarySubject: 'Maths', cards: [{ tags: ['Maths: Quadratics'] }] }; assert.equal(colourForSubject('Maths', { Maths: '#123456' }), '#123456'); assert.equal(colourForSubject('Maths', {}), colourForSubject('Maths', {})); assert.deepEqual(accentForDeck(deck, { Maths: '#123456' }), { subject: 'Maths', fallback: false, colour: '#123456' }); });
test('subject colour choices survive save and load safely', () => { const saved = saveColours({ Biology: '#3c9a88', bad: 'blue' }); assert.deepEqual(loadColours(saved), { Biology: '#3c9a88' }); assert.deepEqual(loadColours('not-json'), {}); });
