const test = require('node:test');
const assert = require('node:assert/strict');
const { answersMatch, selectQuestions, choicesFor, scoreTest, missedQuestions, reviewItems, remainingMs, isExpired, retryQuestions, filterHistory } = require('./test-utils');
const cards = [
  { id: '1', front: 'Abiturfeier (f)', back: 'graduation day' }, { id: '2', front: 'Haus', back: 'house' },
  { id: '3', front: 'Baum', back: 'tree' }, { id: '4', front: 'Wasser', back: 'water' }, { id: '5', front: 'Buch', back: 'book' },
];
test('typed answers ignore case, punctuation, and optional brackets', () => { assert.equal(answersMatch(' abiturfeier ', 'Abiturfeier (f)'), true); assert.equal(answersMatch('GRADUATION DAY!', 'graduation day'), true); assert.equal(answersMatch('party', 'graduation day'), false); });
test('question selection is unique and limited to the available pool', () => { const questions = selectQuestions(cards, 4); assert.equal(questions.length, 4); assert.equal(new Set(questions.map(card => card.id)).size, 4); });
test('multiple choice includes one correct answer and unique distractors', () => { const choices = choicesFor(cards[0], cards, 'front'); assert.equal(choices.includes('graduation day'), true); assert.equal(new Set(choices.map(value => value.toLowerCase())).size, choices.length); assert.ok(choices.length >= 2); });
test('test scoring separates correct, missed, skipped, and unanswered questions', () => { const score = scoreTest({ questions: cards.slice(0, 4), startedAt: '2026-01-01T12:00:00.000Z', endedAt: '2026-01-01T12:01:00.000Z', answers: [{ result: 'correct' }, { result: 'incorrect' }, { result: 'skipped' }] }); assert.deepEqual({ total: score.total, correct: score.correct, incorrect: score.incorrect, skipped: score.skipped, unanswered: score.unanswered, percentage: score.percentage }, { total: 4, correct: 1, incorrect: 1, skipped: 1, unanswered: 1, percentage: 25 }); assert.equal(score.averageMs, 20000); });
test('missed-card sessions contain only wrong or skipped test questions', () => { const missed = missedQuestions({ answers: [{ questionId: '1', result: 'correct' }, { questionId: '2', result: 'incorrect' }, { questionId: '3', result: 'skipped' }] }); assert.deepEqual(missed.map(answer => answer.questionId), ['2', '3']); });
test('timed tests count down and expire exactly at their deadline', () => { const attempt = { deadlineAt: '2026-01-01T12:01:00.000Z' }; assert.equal(remainingMs(attempt, Date.parse('2026-01-01T12:00:35.000Z')), 25000); assert.equal(isExpired(attempt, Date.parse('2026-01-01T12:00:59.999Z')), false); assert.equal(isExpired(attempt, Date.parse('2026-01-01T12:01:00.000Z')), true); });
test('review items include unanswered questions and retries select the intended cards', () => { const attempt = { config: { promptSide: 'front' }, questions: cards.slice(0, 3).map(card => ({ ...card, deckId: 'deck' })), answers: [{ questionId: '1', deckId: 'deck', result: 'correct' }, { questionId: '2', deckId: 'deck', result: 'skipped' }] }; assert.deepEqual(reviewItems(attempt).map(item => item.result), ['correct', 'skipped', 'unanswered']); assert.deepEqual(retryQuestions(attempt).map(card => card.id), ['2', '3']); assert.equal(retryQuestions(attempt, 'all').length, 3); });
test('gender-test review, scoring, and missed retries keep the gender answer', () => { const attempt = { config: { promptSide: 'back' }, questions: [{ id: 'g1', deckId: 'german', front: 'Haus', back: 'house', answerType: 'gender', genderAnswer: 'das' }, { id: 'g2', deckId: 'german', front: 'Katze', back: 'cat', answerType: 'gender', genderAnswer: 'die' }], answers: [{ questionId: 'g1', deckId: 'german', prompt: 'Haus', correctAnswer: 'das', result: 'correct' }, { questionId: 'g2', deckId: 'german', prompt: 'Katze', correctAnswer: 'die', result: 'skipped' }] }; const review = reviewItems(attempt); assert.equal(review[1].prompt, 'Katze'); assert.equal(review[1].correctAnswer, 'die'); assert.equal(scoreTest(attempt).skipped, 1); assert.deepEqual(retryQuestions(attempt).map(question => question.id), ['g2']); });
test('test history filters by deck, folder, date, and score', () => { const attempts = [{ startedAt: '2026-01-10T12:00:00.000Z', summary: { percentage: 100 }, questions: [{ deckId: 'one', folderId: 'f1' }] }, { startedAt: '2025-12-01T12:00:00.000Z', summary: { percentage: 50 }, questions: [{ deckId: 'two', folderId: 'f2' }] }]; const now = Date.parse('2026-01-11T12:00:00.000Z'); assert.equal(filterHistory(attempts, { deckId: 'one', folderId: 'f1', days: 7, score: 'perfect' }, now).length, 1); assert.equal(filterHistory(attempts, { score: '80plus' }, now).length, 1); });
